### PR TITLE
[L0] Use all devices from a context in urProgramBuild

### PR DESCRIPTION
**Pull request by igchor**
Using just the first device makes creating a kernel from that program for any other devices impossible. urEnqueueKernelLaunch fails with UR_RESULT_ERROR_INVALID_QUEUE.

I don't know if using only the first device was intentional or not (perhaps an optimization?) but the test that I added passes for opencl so I think it would make sense to make L0 behave similarly.

### CODE REVIEW

**Comment by nrspruit** [comment]
you copied my review none looked at :) https://github.com/oneapi-src/unified-runtime/pull/1276/files , thanks for making the test change as well.

**Comment by nrspruit** [comment]
Could you add the LinkExp change as well?

**Review by nrspruit — APPROVED** [review]
LGTM, optional to add linkexp

**Comment by igchor** [comment]
> Could you add the LinkExp change as well? or that can wait for a follow-up review.

Sure, done. Actually, there was one other problem with urProgramLink, arguments were passed in wrong order (number od devices and number of program handles)

**Review by pbalcer — APPROVED** [review]

**Pull request merged**
