### PR TITLE
[DeviceSanitizer] Init tracing layer after sanitizer layer to achieve proper tracing

### PR DESCRIPTION
**Pull request by yingcong-wu**
Currently, the tracing layer is inited before sanitizer layer, which means if the sanitizer layer intercepts an API and does not call through layers. The tracing layer will not be able to print the API call.

We should always keep the tracing layer as the last one to be initialized to make sure it is the first layer to handle any API calls so that any API calls would be properly traced.

SYCLOS PR: https://github.com/intel/llvm/pull/15221

### CODE REVIEW

**Review by aarongreig — APPROVED** [review]

**Review by AllanZyne — APPROVED** [review]

**Comment by yingcong-wu** [comment]
Hi @aarongreig , what should I do to move this PR forward? Thank you.

**Review by pbalcer — APPROVED** [review]

**Comment by pbalcer** [comment]
@yingcong-wu CI needs to be green (or mostly green :-))

**Comment by yingcong-wu** [comment]
@pbalcer Sure, thank you. But I just don't see how my PR relates to those failures. I will try to investigate those failures now.

**Comment by pbalcer** [comment]
@yingcong-wu the remaining failures are unrelated. I'll mark this as ready to merge.

**Comment by yingcong-wu** [comment]
Thank you!

**Pull request merged**
