### PR TITLE
[UR] Master merge

### PR DESCRIPTION
**Pull request by hdelan**
Batch merge of PRs:

https://github.com/oneapi-src/unified-runtime/pull/1792
https://github.com/oneapi-src/unified-runtime/pull/1787
https://github.com/oneapi-src/unified-runtime/pull/1782
https://github.com/oneapi-src/unified-runtime/pull/1783
https://github.com/oneapi-src/unified-runtime/pull/1781
https://github.com/oneapi-src/unified-runtime/pull/1773
https://github.com/oneapi-src/unified-runtime/pull/1765
https://github.com/oneapi-src/unified-runtime/pull/1763

### CODE REVIEW

**Comment by JackAKirk** [comment]
LGTM for https://github.com/oneapi-src/unified-runtime/pull/1792 and https://github.com/oneapi-src/unified-runtime/pull/1765

**Comment by hdelan** [comment]
These are all already approved and `Ready to merge` individually so I don't think we need any additional reviews?

**Comment by hdelan** [comment]
At least in this previous batch PR https://github.com/oneapi-src/unified-runtime/pull/1774 we just got an approval from Benie and then it was merged.

**Comment by callumfare** [comment]
@hdelan I don't think we do, I'm happy to merge once tests are all passing. But obviously if anyone wants to check things before then that's ok

**Comment by hdelan** [comment]
I have squashed #1765

**Comment by callumfare** [comment]
The CI jobs all passed before the commits from #1765 were squashed, and the intel/llvm pipeline passed, so I'm merging this now rather than waiting for them to rerun

**Pull request merged**
