### PR TITLE
Address https://github.com/oneapi-src/unified-runtime/issues/800

### PR DESCRIPTION
**Pull request by smaslov-intel**

### CODE REVIEW

**Comment by smaslov-intel** [comment]
@kbenzie , @pbalcer : please review/merge. When merged please update tag here: https://github.com/intel/llvm/blob/d778e56245c8ff2758c5ea56d269f7d12713f616/sycl/plugins/unified_runtime/CMakeLists.txt#L7

**Review by veselypeta — APPROVED** [review]

**Comment by smaslov-intel** [comment]
Who can merge this asap? It's blocking some internal builds from completing.

**Comment by smaslov-intel** [comment]
> @kbenzie , @pbalcer : please review/merge. When merged please update tag here: https://github.com/intel/llvm/blob/d778e56245c8ff2758c5ea56d269f7d12713f616/sycl/plugins/unified_runtime/CMakeLists.txt#L7

I've created https://github.com/intel/llvm/pull/10814

**Comment by igchor** [comment]
Look like we'll need to create a new tag. @smaslov-intel should we do this asap (I think @kbenzie is back tomorrow) or do you expect we'll need some other changes?

**Comment by smaslov-intel** [comment]
> Look like we'll need to create a new tag. @smaslov-intel should we do this asap (I think @kbenzie is back tomorrow) or do you expect we'll need some other changes?

This is the only thing that is needed asap. Does it not work to refer to the commit directly (without creating a tag) as I did in https://github.com/intel/llvm/pull/10814?

**Comment by igchor** [comment]
This should work fine for now, but for the release, it would probably be better to use a tag. @kbenzie can probably comment if there's any significant difference (we may do some extra validation on the tag but I'm not sure if that's true at the moment).

**Pull request merged**
