### PR TITLE
Expand urEventCreateWithNativeHandle

### PR DESCRIPTION
**Pull request by jandres742**
Add needed members for PI:

OwnNativeHandle

### CODE REVIEW

**Comment by jandres742** [comment]
@kbenzie , @pbalcer : do you know why the CI is complaining about format errors in a lot of functions and files not related to my change? like:

```
+###############################################################################
+## @brief Function-pointer for urInit
+if __use_win_types:
+    _urInit_t = WINFUNCTYPE( ur_result_t, ur_device_init_flags_t )
+else:
+    _urInit_t = CFUNCTYPE( ur_result_t, ur_device_init_flags_t )
+
```

**Comment by jandres742** [comment]
I dont get any errors with `python3.exe ./run.py --html` or just make. I haven't been able to run ever other build or generate commands (just config issues on my side).

**Comment by kbenzie** [comment]
Okay, rather than only `python3.exe ./run.py --html` the equivelent to the `generate` target is the follow commands from CMake:

From the `generate-code` target (which should always be available):
https://github.com/oneapi-src/unified-runtime/blob/3bc0f7582453038361d52d26198b3488ed66e6a3/CMakeLists.txt#L229-L230

From the `cppformat` target (which is only enabled when `-DUR_FORMAT_CPP_STYLE=ON` and version 15 of `clang-format` is found, this should be available from the packages installed with [third_party/requirements.txt](https://github.com/oneapi-src/unified-runtime/blob/main/third_party/requirements.txt#L39):
https://github.com/oneapi-src/unified-runtime/blob/3bc0f7582453038361d52d26198b3488ed66e6a3/cmake/helpers.cmake#L30-L33

I think its probably easier to try and fix your local config than run these commands manually.

**Comment by jandres742** [comment]
@kbenzie ready for review. I added a commit addressing the format issues in the CI (I was able to run the generate target locally, but couldn't find reason for that format change).

There are two commits, so it is easy to see the changes associated with the native handle APIs and the changes for the format.

**Review by kbenzie — APPROVED** [review]
LGTM

**Review by callumfare — APPROVED** [review]
LGTM

**Pull request merged**
