### PR TITLE
[ur] Add missing Queue Properties

### LINKED ISSUE #112: Add missing queue properties
# Issue

PI defines the following values for the [`pi_queue_properties`](https://github.com/intel/llvm/blob/c4932957929f94afe7f87bee009eea5e2b5cd6bf/sycl/include/sycl/detail/pi.h#L565) bitfield:
* `PI_EXT_ONEAPI_QUEUE_DISCARD_EVENTS`
* `PI_EXT_ONEAPI_QUEUE_PRIORITY_LOW`
* `PI_EXT_ONEAPI_QUEUE_PRIORITY_HIGH`
which are used [here](https://github.com/intel/llvm/blob/c4932957929f94afe7f87bee009eea5e2b5cd6bf/sycl/source/detail/queue_impl.hpp#L313), [here](https://github.com/intel/llvm/blob/c4932957929f94afe7f87bee009eea5e2b5cd6bf/sycl/source/detail/queue_impl.hpp#L328) and [here](https://github.com/intel/llvm/blob/c4932957929f94afe7f87bee009eea5e2b5cd6bf/sycl/source/detail/queue_impl.hpp#L337) respectively in the DPC++ runtime.

Unified Runtime defines an [`ur_queue_flag_t`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L2124) enumeration but it is missing the above values.

# Task

Add the above enumeration values to `ur_queue_flag_t` so that UR can meeting the requirements of DPC++.

### PR DESCRIPTION
**Pull request by veselypeta**
Adds Queue Properties to unified runtime to support [`sycl_ext_oneapi_discard_queue_events`](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_discard_queue_events.asciidoc) & 
[`sycl_ext_oneapi_queue_priority`](sycl_ext_oneapi_queue_priority).
Closes #112

### CODE REVIEW

**Review by FranklandJack — APPROVED** [review]
LGTM.

**Comment by kbenzie** [comment]
You might not have a good answer but its really not clear to me what an adapter is supposed to do with these flags.

**Comment by veselypeta** [comment]
discard events is explained [here](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_discard_queue_events.asciidoc)
Queue priorities [here](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_queue_priority.asciidoc)

**Comment by kbenzie** [comment]
> discard events is explained [here](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_discard_queue_events.asciidoc) Queue priorities [here](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_queue_priority.asciidoc)
> 
> However both are only implemented on Level Zero I believe.

Okay, this is the kind of thing I'd like to see in commit messages/PR descriptions.

**Review by kbenzie — APPROVED** [review]
LGTM

**Pull request merged**
