### PR TITLE
[L0] Fix usm allocation functions when alignment is not a power of 2

### PR DESCRIPTION
**Pull request by lbushi25**
The Level Zero USM allocation functions are returning non-null pointer values when the alignment is not a power of two which contradicts the spec requirements. This PR fixes that. For more info, see https://github.com/intel/llvm/issues/12638

### CODE REVIEW

**Comment by nrspruit** [comment]
Hello @lbushi25 ,

Please file a Draft PR in intel/llvm pointing to this change such that the pre-commit CI in intel/llvm e2e can be run.

I did not see anything directly that was an issue, but please add that PR with this PR mentioned in the commit message. Thank you for your time and contribution!

**Comment by nrspruit** [comment]
> Hi @nrspruit , I've already opened an intel/llvm PR here [intel/llvm#13631](https://github.com/intel/llvm/pull/13631) but looks like I forgot to mention it here.

Thank you, can you rebase your changes here and in the intel/llvm PR? Since the intel/llvm PR has a merge conflict. Otherwise looks good to me and I can approve. Thank you for your contirbution.

**Comment by lbushi25** [comment]
> > Hi @nrspruit , I've already opened an intel/llvm PR here [intel/llvm#13631](https://github.com/intel/llvm/pull/13631) but looks like I forgot to mention it here.
> 
> Thank you, can you rebase your changes here and in the intel/llvm PR? Since the intel/llvm PR has a merge conflict. Otherwise looks good to me and I can approve. Thank you for your contribution.

Yes, the rebase is done.

**Review by nrspruit — APPROVED** [review]
LGTM and CI is now passing, I will label this as ready to merge.

**Pull request merged**
