### PR TITLE
[DeviceSanitizer] Support detecting misaligned access error

### PR DESCRIPTION
**Pull request by AllanZyne**
LLVM: https://github.com/intel/llvm/pull/14148

### CODE REVIEW

**Review by yingcong-wu — APPROVED** [review]

**Comment by yingcong-wu** [comment]
Could we add an option to turn this off when needed?

**Review by zhaomaosu — APPROVED** [review]
lgtm

**Comment by AllanZyne** [comment]
> Could we add an option to turn this off when needed?

We can discuss this in the future.

**Comment by AllanZyne** [comment]
Hi @oneapi-src/unified-runtime-maintain, please review this PR.
Thanks!

**Comment by kbenzie** [comment]
Need to have the https://github.com/intel/llvm/pull/14148 checks passing.

**Comment by AllanZyne** [comment]
> Need to have the [intel/llvm#14148](https://github.com/intel/llvm/pull/14148) checks passing.

I can sync that branch to latest code, but those CI check failures are not related to my PR.

**Comment by AllanZyne** [comment]
> > > Need to have the [intel/llvm#14148](https://github.com/intel/llvm/pull/14148) checks passing.
> > 
> > 
> > I can sync that branch to latest code, but those CI check failures are not related to my PR.
> 
> No matter if they are related to your changes or not, the checks must still all pass before gatekeepers will press the merge button. Likewise, we won't merge to UR until intel/llvm checks are all passing.

Updated. Thanks!

**Pull request merged**
