### PR TITLE
[Coverity][L0] Remove overlapping mem copy in urBindlessImagesSampledImageCreateExp

### PR DESCRIPTION
**Pull request by wenju-he**
Tested in https://github.com/intel/llvm/pull/12965

### CODE REVIEW

**Comment by wenju-he** [comment]
@kbenzie could you please review? thank you

**Comment by isaacault** [comment]
Is there a draft DPC++ PR for this as per the [adapter change process](https://oneapi-src.github.io/unified-runtime/core/CONTRIB.html#adapter-change-process)?

**Comment by wenju-he** [comment]
> Is there a draft DPC++ PR for this as per the [adapter change process](https://oneapi-src.github.io/unified-runtime/core/CONTRIB.html#adapter-change-process)?

I'm afraid this is impossible since spirv part of device functions in https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/ext/oneapi/bindless_images.hpp are not added yet. This means end-2-end test can't run on Intel DG2 GPU as the tests would fail in device code compilation stage.

**Comment by pbalcer** [comment]
> > Is there a draft DPC++ PR for this as per the [adapter change process](https://oneapi-src.github.io/unified-runtime/core/CONTRIB.html#adapter-change-process)?
> 
> I'm afraid this is impossible since spirv part of device functions in https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/ext/oneapi/bindless_images.hpp are not added yet. This means end-2-end test can't run on Intel DG2 GPU as the tests would fail in device code compilation stage.

We cannot merge changes into UR that would break upstream SYCL, since that would block updating UR in SYCL. Please indicate in the PR description that this requires other PRs to first be merged.

**Comment by wenju-he** [comment]
> > > Is there a draft DPC++ PR for this as per the [adapter change process](https://oneapi-src.github.io/unified-runtime/core/CONTRIB.html#adapter-change-process)?
> > 
> > 
> > I'm afraid this is impossible since spirv part of device functions in https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/ext/oneapi/bindless_images.hpp are not added yet. This means end-2-end test can't run on Intel DG2 GPU as the tests would fail in device code compilation stage.
> 
> We cannot merge changes into UR that would break upstream SYCL, since that would block updating UR in SYCL. Please indicate in the PR description that this requires other PRs to first be merged.

This PR only fixes a coverity issue in UR.

Regarding intel/llvm repo this PR is a NFC change, because sycl bindless image tests in intel/llvm are not enabled on DG2 at all.

While we're waiting for dependent patch for sycl header that can enables end-2-end testing on DG2, we do have local version of the dependent patch for sycl headers, and the current support of bindless image in L0 adaptor enables us to debugging on DG2. The support is very helpful since it enables concurrent debugging from multiple people.

**Review by isaacault — APPROVED** [review]
I see this is just a coverity fix - LGTM.

I'm aware the bindless images SPIR-V isn't added yet, and thus the DPC++ CI wouldn't hit this, making it NFC regardless. I'll leave it to the UR merge team to decide if we still need to follow the process.

**Review by przemektmalon — APPROVED** [review]

**Review by Seanst98 — APPROVED** [review]

**Pull request merged**
