### PR TITLE
Enable fp16 runtime support for hip

### PR DESCRIPTION
**Pull request by MartinWehking**
Needed for https://github.com/intel/llvm/pull/11626

### CODE REVIEW

**Comment by ldrumm** [comment]
Does this feature need to be enabled conditionally depending on the arch properties?

**Comment by MartinWehking** [comment]
@ldrumm The only problematic one is Tahiti, which doesn't support fp16, but we decided to ignore Tahiti in this case.
There's unfortunately no possibility to query fp16 support dynamically (for fp64 there's a member inside 'hipDeviceArch_t', rocm/include/hip/hip_runtime_api.h, but not for fp16)

**Comment by JackAKirk** [comment]
> Tahiti

Tahiti is not officially supported by ROCm anyway. This should be fine.

**Review by JackAKirk — APPROVED** [review]

**Comment by fabiomestre** [comment]
I have updated the target branch of this PR from the `adapters` branch to the `main` branch.
Development in UR is moving back to `main`. The `adapters` branch will soon be deleted.

**Pull request merged**
