### PR TITLE
disable clang build for L0 adapter tests

### PR DESCRIPTION
**Pull request by pbalcer**

### CODE REVIEW

**Comment by pbalcer** [comment]
I tried a different workaround in #1484 to always build the loader using GCC. That proved futile and resulted in tests not seeing any platforms at all. Having wasted enough time on this already, for now I'm proposing we just disable L0 clang tests until the loader/L0 issue is resolved.

**Review by kbenzie — APPROVED** [review]

**Review by lukaszstolarczuk — APPROVED** [review]

**Comment by lukaszstolarczuk** [comment]
@kbenzie are you ok with merging this right away? I could add more Intel runners after that

**Comment by kbenzie** [comment]
> @kbenzie are you ok with merging this right away? I could add more Intel runners after that

Yeah, sure. Since you're making infra changes I'll probably need to cherry-pick this to the release branch so that testing keeps working as well. Is that correct?

**Comment by lukaszstolarczuk** [comment]
> > @kbenzie are you ok with merging this right away? I could add more Intel runners after that
> 
> Yeah, sure. Since you're making infra changes I'll probably need to cherry-pick this to the release branch so that testing keeps working as well. Is that correct?

yes, right. I hold on with new runners until you cherry-pick this.

**Comment by kbenzie** [comment]
> > > @kbenzie are you ok with merging this right away? I could add more Intel runners after that
> > 
> > 
> > Yeah, sure. Since you're making infra changes I'll probably need to cherry-pick this to the release branch so that testing keeps working as well. Is that correct?
> 
> yes, right. I hold on with new runners until you cherry-pick this.

[Done](https://github.com/oneapi-src/unified-runtime/pull/1519/commits/0f41ecb4773d6683861a2881d7abc1c15d152c62). Please go ahead with adding the runners 🙂

**Pull request merged**
