### PR TITLE
[L0] Disabling Driver In Order Lists by default

### PR DESCRIPTION
**Pull request by nrspruit**
- Due to L0 Driver issues related to performance using driver in order lists, the feature is being disabled for the time being.
- Once issues with the L0 Drivers implementing this feature are resolved, then this feature will be re-enabled.

### CODE REVIEW

**Review by pbalcer — APPROVED** [review]

**Comment by EwanC** [comment]
In command-buffer code we use `ZE_COMMAND_LIST_FLAG_IN_ORDER` command-lists without a precondition on this `useDriverInOrderLists()` check (https://github.com/oneapi-src/unified-runtime/blob/3fdf7e3998b029fbf6cdb584e552a71a678f3146/source/adapters/level_zero/command_buffer.cpp#L575). Is that something that will suffer from the problem that's motivating this change?

**Comment by Bensuo** [comment]
> In command-buffer code we use `ZE_COMMAND_LIST_FLAG_IN_ORDER` command-lists without a precondition on this `useDriverInOrderLists()` check (it's based on a flag passed from SYCL-RT)
> 
> https://github.com/oneapi-src/unified-runtime/blob/3fdf7e3998b029fbf6cdb584e552a71a678f3146/source/adapters/level_zero/command_buffer.cpp#L575
> Is that something that will suffer from the problem that's motivating this change?

We do the same check [here](https://github.com/oneapi-src/unified-runtime/blob/3fdf7e3998b029fbf6cdb584e552a71a678f3146/source/adapters/level_zero/command_buffer.cpp#L599) that's removed in this PR to confirm whether we can use inorder command lists or not, so I would guess that should also be changed.

**Comment by nrspruit** [comment]
> In command-buffer code we use `ZE_COMMAND_LIST_FLAG_IN_ORDER` command-lists without a precondition on this `useDriverInOrderLists()` check (it's based on a flag passed from SYCL-RT)
> 
> https://github.com/oneapi-src/unified-runtime/blob/3fdf7e3998b029fbf6cdb584e552a71a678f3146/source/adapters/level_zero/command_buffer.cpp#L575
> 
> . Is that something that will suffer from the problem that's motivating this change?

If this is based on a flag passed from SYCL RT, then it should not be changed. This is about changing the default behavior to use standard lists and not in order by default.

**Comment by nrspruit** [comment]
Ah, I missed the "canBeInOrder" let me change that too.

**Comment by nrspruit** [comment]
@EwanC , please check the command buffer changes, now both are disabled for now.

**Comment by nrspruit** [comment]
> @EwanC , please check the command buffer changes, now both are disabled for now.

had a problem in my patch, please re-check, unfortunately this will disable driver in order in command buffer for now until the driver issues can be resolved.

**Comment by nrspruit** [comment]
@EwanC / @Bensuo please re-review so we can get this change in as soon as possible to create the release branch.

This updated PR will disable in both common code and command buffers.

**Comment by Bensuo** [comment]
> @EwanC / @Bensuo please re-review so we can get this change in as soon as possible to create the release branch.
> 
> This updated PR will disable in both common code and command buffers.



> @EwanC / @Bensuo please re-review so we can get this change in as soon as possible to create the release branch.
> 
> This updated PR will disable in both common code and command buffers.

I'm not sure offhand why we don't have this already, but could you add the check for `UR_L0_USE_DRIVER_INORDER_LISTS` to `canBeInOrder()` so that we can still enable them if needed? Since that's still in the general implementation I think that should be fine for now.

**Comment by nrspruit** [comment]
> > @EwanC / @Bensuo please re-review so we can get this change in as soon as possible to create the release branch.
> > This updated PR will disable in both common code and command buffers.
> 
> I'm not sure offhand why we don't have this already, but could you add the check for `UR_L0_USE_DRIVER_INORDER_LISTS` to `canBeInOrder()` so that we can still enable them if needed? Since that's still in the general implementation I think that should be fine for now.

Ok, let me add that in such that in both cases it is "possible" to use the feature.

**Review by Bensuo — APPROVED** [review]
LGTM, thanks for making those changes!

**Comment by nrspruit** [comment]
> > > @EwanC / @Bensuo please re-review so we can get this change in as soon as possible to create the release branch.
> > > This updated PR will disable in both common code and command buffers.
> > 
> > 
> > I'm not sure offhand why we don't have this already, but could you add the check for `UR_L0_USE_DRIVER_INORDER_LISTS` to `canBeInOrder()` so that we can still enable them if needed? Since that's still in the general implementation I think that should be fine for now.
> 
> Ok, let me add that in such that in both cases it is "possible" to use the feature.

@EwanC , I have updated the check in command buffer such that it also checks the env for driver in order. This will enable both paths to work now.

**Comment by nrspruit** [comment]
This change is ready to merge, but we are fighting CI issues with a very long delay in execution.

**Comment by EwanC** [comment]
Sorry @nrspruit I logged off for the day after leaving that comment so didn't see your replies, but Ben has reviewed this on behalf of the command-buffer group and happy with the final patch.

**Pull request merged**
