### PR TITLE
[L0] Update Level Zero Loader version to v1.18.5

### PR DESCRIPTION
**Pull request by nrspruit**

### CODE REVIEW

**Review by igchor — APPROVED** [review]

**Comment by EwanC** [comment]
I tested this out locally, and still see the `SYCL Exception encountered: Native API failed. Native API returns: 2147483646 (UR_RESULT_ERROR_UNKNOWN)` error running sycl-ls

**Comment by nrspruit** [comment]
> I tested this out locally, and still see the `SYCL Exception encountered: Native API failed. Native API returns: 2147483646 (UR_RESULT_ERROR_UNKNOWN)` error running sycl-ls

Let me check, I wonder if we are having a conflict since MCL symbols are now included.

**Comment by nrspruit** [comment]
> > I tested this out locally, and still see the `SYCL Exception encountered: Native API failed. Native API returns: 2147483646 (UR_RESULT_ERROR_UNKNOWN)` error running sycl-ls
> 
> Let me check, I wonder if we are having a conflict since MCL symbols are now included.

We know this is working correctly with older drivers and libraries, so this must be specific to this configuration.

**Review by EwanC — APPROVED** [review]
Discovered that the error I'm seeing is to do with a DPC++ build issue I've documented in https://github.com/intel/llvm/issues/15986

**Pull request merged**
