### PR TITLE
Change `urSuggestMaxCooperativeGroupCountExp` to accept ND size parameter

### PR DESCRIPTION
**Pull request by 0x12CC**
The L0 API requires calling `zeKernelSetGroupSize` before `zeKernelSuggestMaxCooperativeGroupCount` to ensure that the query result is correct. This PR changes `urSuggestMaxCooperativeGroupCountExp` to accept a group size with `uint32_t *pworkDim` and `const size_t **ppLocalWorkSize` parameters.

### CODE REVIEW

**Review by steffenlarsen — APPROVED** [review]
CUDA and HIP changes LGTM!

**Review by nrspruit — APPROVED** [review]
Level Zero LGTM.

**Review by aarongreig — APPROVED** [review]

**Comment by aarongreig** [comment]
> All SYCL tests for this PR are passing in [intel/llvm#16051](https://github.com/intel/llvm/pull/16051).

if you can get that PR approved by `llvm-reviewers-runtime` I'll mark this one as ready to merge

**Comment by aarongreig** [comment]
> @aarongreig, there's now an approval from `llvm-reviewers-runtime` here: [intel/llvm#16051 (review)](https://github.com/intel/llvm/pull/16051#pullrequestreview-2469125199).

I've added the label, just to manage your expectations: [the queue](https://github.com/oneapi-src/unified-runtime/pulls?q=is%3Aopen+is%3Apr+label%3A%22ready+to+merge%22) is quite busy at the moment so there will be a wait to get merged

**Pull request merged**
