### PR TITLE
Implement Queue Flush operation

### PR DESCRIPTION
**Pull request by lbushi25**
This PR implements the method urQueueFlush for L0 plugin.

### CODE REVIEW

**Review by nrspruit — APPROVED** [review]

**Comment by lbushi25** [comment]
@nrspruit Hey, its my first time contributing here!
After the workflow is approved and succeeds, who do I have to tag to get this merged?
Thanks!

**Comment by nrspruit** [comment]
> @nrspruit Hey, its my first time contributing here! After the workflow is approved and succeeds, who do I have to tag to get this merged? Thanks!

Hello @lbushi25 , I just triggered the workflow, please have @AlexeySachkov also review since he was your primary reviewer on the intel/llvm changes. Once approved and the CI both here and in intel/llvm passes, then we can add the tag to get your change in the queue to be merged with "ready_to_merge" .

**Comment by againull** [comment]
LGTM, I don't have ability to self-request review on this pr.

**Comment by lbushi25** [comment]
@pbalcer When can I expect this to be merged?
I need the merge to bump up the UR tag on https://github.com/intel/llvm/pull/13555

**Comment by againull** [comment]
@lbushi25 I think you accidentally pushed wrong changes to the this PR.

**Comment by lbushi25** [comment]
> @lbushi25 I think you accidentally pushed wrong changes to the this PR.

Oops did not notice this, thanks for the heads up!

**Pull request merged**
