### PR TITLE
[DeviceSanitizer] Extend a variable lifetime to fix a flaky failure

### PR DESCRIPTION
**Pull request by yingcong-wu**
`EnqueueWriteGlobal` is a async write, so `&Debug`'s content is undetermined at the time of writing. Therefore we need to extend its lifetime to make it work.

### CODE REVIEW

**Comment by yingcong-wu** [comment]
Do we still need a SYCLOS PR for this minor change?

**Comment by pbalcer** [comment]
This should probably be a heap allocation, not a static. Right now this is not MT-safe.

**Comment by yingcong-wu** [comment]
> `debug` should probably be a heap allocation, not a static. Right now this is not MT-safe.

Yes, that is correct, I will rework on this patch.

**Comment by yingcong-wu** [comment]
Hi @pbalcer , the debug value will no change during the entire program's lifetime, and now we only doing the initialization once, and no other write operation. I think that makes it MT-safe.

**Review by pbalcer — APPROVED** [review]
oh, right, you are reading from this variable, not writing to it :)
I'd still prefer a heap allocation over a global, but this should work.

**Comment by yingcong-wu** [comment]
Hi @pbalcer , could you please help land this patch? Thanks.

**Comment by yingcong-wu** [comment]
Hi @pbalcer , this bugfix would need to target 2025.0, what do I need to do to ensure this fix would be included?

**Comment by yingcong-wu** [comment]
Kindly ping @pbalcer , could you please provide some information about how to make sure this fix is included in 2025.0?

**Comment by pbalcer** [comment]
> Kindly ping @pbalcer , could you please provide some information about how to make sure this fix is included in 2025.0?

We still haven't tagged a release branch, and, once we do, this will be included. So no worries.

**Comment by yingcong-wu** [comment]
> > Kindly ping @pbalcer , could you please provide some information about how to make sure this fix is included in 2025.0?
> 
> We still haven't tagged a release branch, and, once we do, this will be included. So no worries.

Great! Thank you!

**Comment by yingcong-wu** [comment]
Hi @pbalcer , I now that we have a lot of work going on here, and this is just a friendly reminder to please not forget to cherry-pick to v0.10.0rc, thank you so much.

**Pull request merged**
