### PR TITLE
fix permissions in e2e workflow

### PR DESCRIPTION
**Pull request by pbalcer**
Ref: #1719

### CODE REVIEW

**Review by kbenzie — APPROVED** [review]

**Comment by kbenzie** [comment]
From the [comment](https://github.com/oneapi-src/unified-runtime/pull/1719#issuecomment-2152250416) it looked like the commits were already on `main`...

**Comment by pbalcer** [comment]
@kbenzie When you closed your PR I assumed you wanted me to create the PR instead :)

**Comment by kbenzie** [comment]
> @kbenzie When you closed your PR I assumed you wanted me to create the PR instead :)

Spinning too many plates 😅

**Comment by pbalcer** [comment]
@lukaszstolarczuk This seems to have worked on your fork, but you had pr write permission: https://github.com/lukaszstolarczuk/unified-runtime/pull/7/files#diff-c68dec5b230f8243fe4144d52e61bbad25a1aecad217e3a1efab02195e8e8713R56 Any reason you changed that or just accident?

**Review by lukaszstolarczuk — APPROVED** [review]
yeah, sorry, by accident. I was just about to move the permissions from the top-level one in `e2e_core.yml` to "per job" permissions (in line 76).

The top level permission in `cmake.yml` are for sure missing on main, the other one I'm not sure if it's needed (but it can't hurt 😉 ).

**Pull request merged**
