### PR TITLE
[HIP] Add missing symbols hip

### PR DESCRIPTION
**Pull request by hdelan**
The global exported symbols are here https://github.com/oneapi-src/unified-runtime/blob/adapters/source/adapters/adapter.map.in

This file https://github.com/oneapi-src/unified-runtime/blob/adapters/source/adapters/hip/ur_interface_loader.cpp is missing some symbols that are written in the lib map. This caused a linker error for LLD when linking in DPC++. This patch adds them, fixing the linker error.

### CODE REVIEW

**Comment by kbenzie** [comment]
The testing doesn't like this change, will need to investigagte that before we can merge.

**Comment by hdelan** [comment]
> The testing doesn't like this change, will need to investigagte that before we can merge.

Investigating

**Comment by pbalcer** [comment]
Looking at the loader implementation, it expects the addr table to at least be null-initialized.

**Comment by pbalcer** [comment]
It also just occurred to me that you can't return an error from these functions if you want the adapter to be functional. Once once get table function fails, the rest of them are skipped (https://github.com/oneapi-src/unified-runtime/blob/main/source/loader/ur_ldrddi.cpp#L8626).

I think we have a bug that such platform is then made accessible to the user.

**Comment by hdelan** [comment]
> It also just occurred to me that you can't return an error from these functions if you want the adapter to be functional. Once one get table function fails, the rest of them are skipped (https://github.com/oneapi-src/unified-runtime/blob/main/source/loader/ur_ldrddi.cpp#L8626).
> 
> I think we have a bug that such platform is then made accessible to the user.

Yeah the testing passes if you change retail to `UR_RESULT_SUCCESS`. I'm not sure if this is desirable but have added a comment in the code to say we need this to return `UR_RESULT_SUCCESS` or else platform initialisation will fail.

**Comment by hdelan** [comment]
@kbenzie any word on this? Would be nice to fix lld builds in DPC++

**Review by pbalcer — APPROVED** [review]

**Review by mmoadeli — COMMENTED** [review]
Is there any need for a (warning or error ) message inside the functions annotated with `// TODO: Implement` ?

**Comment by kbenzie** [comment]
> @kbenzie any word on this? Would be nice to fix lld builds in DPC++

We need to prioritise merging PR's for the next release which this isn't targetted for. Will aim to merge this after we've drained that release PR backlog.

**Pull request closed without merging**
