### PR TITLE
Refactor opencl adapter to new logger 

### PR DESCRIPTION
**Pull request by lplewa**

### CODE REVIEW

**Comment by lplewa** [comment]
I created an octopus merge b45470f9e1a5c4bacbc210d68e900858b82fae25 of all logs changes (#1359; #1347; #1345; #1342; #1032) and tested integration with [intel/llvm repository](https://github.com/intel/llvm/pull/12580/files)

**Comment by lplewa** [comment]
@oneapi-src/unified-runtime-opencl-write - please review - if you are ok with changes please label it as ready to merge

**Review by kbenzie — APPROVED** [review]

**Comment by kbenzie** [comment]
> @oneapi-src/unified-runtime-opencl-write - please review - if you are ok with changes please label it as ready to merge

appologies for the lateness

**Comment by pbalcer** [comment]
To reduce risk, ideally this would be merged after 0.9 is branched off.

**Pull request merged**
