### PR TITLE
[ur] add ur prefix to target names

### PR DESCRIPTION
**Pull request by igchor**
Target name can show up in a linker .map file.
Having appropirate prefixes makes it easier to
identify the component.

### CODE REVIEW

**Comment by DamianDuy** [comment]
LGTM

**Review by pbalcer — APPROVED** [review]

**Comment by pbalcer** [comment]
please rebase

**Comment by pbalcer** [comment]
Also, we should probably add linker version scripts to avoid accidentally exporting unneeded symbols.

**Comment by igchor** [comment]
Rebased

**Pull request merged**
