### PR TITLE
[CL] Gracefully tear down adapter in case that some globals have been released

### PR DESCRIPTION
**Pull request by zhaomaosu**
Sometimes the adapter may exit before sycl lib, if sycl lib calls urAdapterRelease later it may cause segment fault since some globals already have been released.

intel/llvm: https://github.com/intel/llvm/pull/12992

### CODE REVIEW

**Comment by kbenzie** [comment]
Firstly, I did not mean to close this. I pressed the wrong button.

> Hi @oneapi-src/unified-runtime-opencl-write, could you please help review this PR? It will fix an urgent issue, and the changes are quite simple. Thanks.

If you could share what issue this relates to I'd appriciate it, by email if necessary.

Secondly, there appears to be a number of test failures in https://github.com/intel/llvm/pull/12992 which will need to be resolved before we can approve this PR.

**Comment by zhaomaosu** [comment]
Hi @kbenzie, thanks for your comments.

> If you could share what issue this relates to I'd appriciate it, by email if necessary.

Already sent an email to you for sharing more details.

> Secondly, there appears to be a number of test failures in [intel/llvm#12992](https://github.com/intel/llvm/pull/12992) which will need to be resolved before we can approve this PR.

intel/llvm pre-ci failures have been fixed. But there is one failure in UR pre-ci, looks like it's fuzzing test https://github.com/oneapi-src/unified-runtime/actions/runs/8259996916/job/22594778917?pr=1431. I cannot reproduce it locally, not sure if it's a known issue ?

**Comment by zhaomaosu** [comment]
For the segment fault in fuzz test suite, I cannot reproduce it locally:

```
$ ctest -C Release --output-on-failure -L "fuzz-short"
Test project /export/users/maosuzha/ics_workspace/unified-runtime/build
    Start  99: fuzztest-alloc
1/4 Test  #99: fuzztest-alloc ...................   Passed    0.04 sec
    Start 100: fuzztest-create-release
2/4 Test #100: fuzztest-create-release ..........   Passed    0.05 sec
    Start 101: fuzztest-kernel-launch
3/4 Test #101: fuzztest-kernel-launch ...........   Passed    0.03 sec
    Start 102: fuzztest-pool-alloc
4/4 Test #102: fuzztest-pool-alloc ..............   Passed    0.04 sec

100% tests passed, 0 tests failed out of 4

Label Time Summary:
fuzz-short    =   0.16 sec*proc (4 tests)

Total Test time (real) =   0.17 sec
```

Not sure if it's a coincidental ci infrastructure issue.

**Comment by pbalcer** [comment]
It might be accidental, fuzz tests don't run with OpenCL yet. It's a fuzz test after all (however, the short CI run should be deterministic, so...).

**Comment by kbenzie** [comment]
> intel/llvm pre-ci failures have been fixed. But there is one failure in UR pre-ci, looks like it's fuzzing test https://github.com/oneapi-src/unified-runtime/actions/runs/8259996916/job/22594778917?pr=1431. I cannot reproduce it locally, not sure if it's a known issue ?

I missed this, sorry.

> It might be accidental, fuzz tests don't run with OpenCL yet. It's a fuzz test after all (however, the short CI run should be deterministic, so...).

Something to keep an eye on to see if it pops up regularly, I guess.

I suspect this fix may not be the best long term solution, it feels like it may be related to #1425 which points to a larger issue.

I'm open to merging this to alleviate the immediate issue but we may replace it a different fix later on to work for all adapters.

I'll hold off merging until later today after further discussions are had.

**Review by kbenzie — APPROVED** [review]

**Pull request merged**
