### PR TITLE
[CTS] Added test for sequencing events

### PR DESCRIPTION
**Pull request by RossBrunton**
This tests that the `urEnqueueEventsWaitWithBarrier` function
functions as a barrier. That is, it blocks until all events prior
to it in the queue are completed. Since this test may fail
non-deterministically, it is ran a few times.

Note that current adapters seem to always execute events
sequentially, so this is a no-op.

### CODE REVIEW

**Review by aarongreig — APPROVED** [review]

**Comment by RossBrunton** [comment]
@aarongreig You had a look at this way back in May, but it's been tweaked a bit since then. Mind giving it another look over just to ensure everything is still okay?

**Comment by aarongreig** [comment]
actually did you look into what's up with the level zero fail? in case it's something trivial

**Comment by pbalcer** [comment]
> actually did you look into what's up with the level zero fail? in case it's something trivial

I was meaning to ask the same question. If barriers don't work in the L0 adapter, we need to fix that asap.

**Comment by RossBrunton** [comment]
Looks like it was complaining about the test not failing when the match file said it should. Probably due to an earlier version of the test being broken (I was breaking this rule https://github.com/oneapi-src/unified-runtime/pull/2195 ).

Hopefully this means that it's all actually passing on non-native-cpu targets.

**Comment by RossBrunton** [comment]
Only adds conformance tests so should have no effect on intel/llvm. Merging without llvm change.

**Pull request merged**
