### PR TITLE
[HIP] Implement ext_oneapi_queue_priority

### PR DESCRIPTION
**Pull request by al42and**

### CODE REVIEW

**Comment by al42and** [comment]
intel/llvm CI here https://github.com/intel/llvm/pull/11622

**Review by mmoadeli — APPROVED** [review]
LGTM

**Comment by al42and** [comment]
Is there anything else left to do before this PR can get merged?

**Comment by kbenzie** [comment]
> Is there anything else left to do before this PR can get merged?

I'll add the *ready to merge* label once the checks pass on the latest changes, then it'll be added to our merge queue. Once this is merged I'll request changes on https://github.com/intel/llvm/pull/11622 to point at the merged commit and to integrate the changes over there.

**Comment by kbenzie** [comment]
Having some CI issues, I'll come back to this and retry the jobs once we've cleared the job backlog.

**Comment by fabiomestre** [comment]
I have updated the target branch of this PR from the `adapters` branch to the `main` branch.
Development in UR is moving back to `main`. The `adapters` branch will soon be deleted.

**Comment by al42and** [comment]
Thanks, @fabiomestre. Any actions needed from me?

**Comment by kbenzie** [comment]
Unforutately this has caused a regression on main so reverting, will aim to fix that up and get it merged soon.

**Comment by al42and** [comment]
@kbenzie: Yeah, this change has rotten a bit :(
I'll make suggestions to #1229 with the necessary fixes.

**Pull request merged**
