### PR TITLE
[UR][L0] Prefer to build to a device in the context where the first(!…

### PR DESCRIPTION
**Pull request by nrspruit**
…) queue is created

### CODE REVIEW

**Comment by nrspruit** [comment]
Pre merge testing of this change thru the Draft PR: https://github.com/intel/llvm/pull/11336/

**Comment by jandres742** [comment]
> Pre merge testing of this change thru the Draft PR: [intel/llvm#11336](https://github.com/intel/llvm/pull/11336)

thanks @nrspruit

**Comment by jandres742** [comment]
We are confirming changes are good with other workloads we have before proceeding.

**Review by veselypeta — APPROVED** [review]

**Comment by jandres742** [comment]
we no longer need this. Closing.

**Pull request closed without merging**
