### PR TITLE
Correct level of indirection used in KernelSetArgPointer calls.

### LINKED ISSUE #558: Clarify urKernelSetArgPointer spec
We have the urKernelSetArgPointer entry point to pass USM allocations as parameters to kernels. To get an idea of how this is set up we have these function signatures for some of the relevant entry points:
```
ur_result_t urUSMDeviceAlloc(ur_context_handle_t hContext, ur_device_handle_t hDevice,
                             const ur_usm_desc_t *pUSMDesc, ur_usm_pool_handle_t pool,
                             size_t size, void **ppMem)

ur_result_t urKernelSetArgPointer(ur_kernel_handle_t hKernel, uint32_t argIndex,
                                  const void *pArgValue)
```
Based on this, and the spec description for `urKernelSetArgPointer`'s `pArgValue` parameter
> [in][optional] USM pointer to memory location holding the argument value. If null then argument value is considered null.

Correct usage could look like this
```
void* allocation = nullptr;
size_t allocation_size = 32;

urUSMDeviceAlloc(context, device, nullptr, nullptr,
                 allocation_size, &allocation);

urKernelSetArgPointer(kernel, 0, allocation);
```
or this
```
void* allocation = nullptr;
size_t allocation_size = 32;

urUSMDeviceAlloc(context, device, nullptr, nullptr,
                 allocation_size, &allocation);

urKernelSetArgPointer(kernel, 0, &allocation);
```
depending on whether you put emphasis on
> [in][optional] **USM pointer** to memory location holding the argument value. If null then argument value is considered null.

or
> [in][optional] USM **pointer to memory location holding the argument** value. If null then argument value is considered null.

While implementing tests that make direct use of these entry points I've found that existing implementations expect the latter usage, and by extension this is also how the sycl runtime makes use of the analogous PI entry point.

This could do with some clarification. The wording can be changed to be more explicit, and to better match how USM pointers are passed around elsewhere it might make sense to change the function signature to this
```
ur_result_t urKernelSetArgPointer(ur_kernel_handle_t hKernel, uint32_t argIndex,
                                  void **pArgValue)
```

I would also suggest that how this is currently expected to work is... weird. Because of how the allocation entry points work, and how passing USM pointers to any other entry point works (see `urEnqueueUSMMemcpy` etc.), I found this behaviour pretty surprising. It would take some refactor work across all the UR adapters and unported plugins as well as the sycl runtime itself, but I think it's worth considering whether we should make the former usage in the above examples the expected behaviour, in the interest of making the library more intuitive.

### PR DESCRIPTION
**Pull request by aarongreig**
Also attempt to clarify the wording around this a bit.

fixes #558

LLVM testing https://github.com/intel/llvm/pull/12270

### CODE REVIEW

**Review by martygrant — APPROVED** [review]

**Review by fabiomestre — APPROVED** [review]

**Review by kbenzie — APPROVED** [review]

**Comment by aarongreig** [comment]
I was able to properly test this on more than just cuda this morning and I can confirm this will need a small patch for the cuda and opencl adapters when it gets into intel-llvm. Maybe merging this should wait until the adapters move in here and they can be patched simultaneously?

**Comment by kbenzie** [comment]
> Maybe merging this should wait until the adapters move in here and they can be patched simultaneously?

That makes sense, convert this to draft so we don't merge it unintentionally.

**Review by nrspruit — APPROVED** [review]
LGTM for level zero

**Review by kbenzie — APPROVED** [review]

**Comment by kbenzie** [comment]
@oneapi-src/unified-runtime-native-cpu-write @mmoadeli would be great to get your reviews on this.

**Review by PietroGhg — APPROVED** [review]
Native CPU lgtm, thank you

**Comment by kbenzie** [comment]
@oneapi-src/unified-runtime-cuda-write @oneapi-src/unified-runtime-hip-write would appriciate a review on this, the CUDA/HIP changes are very small.

**Review by jchlanda — APPROVED** [review]
CUDA/HIP 👍

**Review by EwanC — APPROVED** [review]

**Comment by kbenzie** [comment]
I've removed *ready to merge* since the CUDA checks aren't passing, please add it again once they go green.

**Pull request merged**
