### PR TITLE
Update CodeQL to v3.25.7

### PR DESCRIPTION
**Pull request by pbalcer**
CodeQL started failing on Windows. Hoping a simple update fixes the problem.

### CODE REVIEW

**Review by kbenzie — APPROVED** [review]

**Comment by pbalcer** [comment]
Well, it didn't help :( We might need to disable this job for now. I trigger a rerun of a previously successful job on main:
https://github.com/oneapi-src/unified-runtime/actions/runs/9321220672/job/25735621065

**Comment by kbenzie** [comment]
> Well, it didn't help :( We might need to disable this job for now. I triggered a rerun of a previously successful job on main: https://github.com/oneapi-src/unified-runtime/actions/runs/9321220672/job/25735621065

Looks like this passed, does that mean there's actually a CodeQL issue and the reporting mechanism is somehow broken?

**Comment by pbalcer** [comment]
> > [](https://github.com/oneapi-src/unified-runtime/actions/runs/9321220672/job/25735621065)
> 
> Looks like this passed, does that mean there's actually a CodeQL issue and the reporting mechanism is somehow broken?

Hard to say. The only relevant difference between main and say, https://github.com/oneapi-src/unified-runtime/pull/1701, is different origin branch. Can you merge #1701 to see if the CodeQL build on main passes?

**Comment by kbenzie** [comment]
#1692 has passed out of the blue also. Very odd.

**Comment by pbalcer** [comment]
CodeQL on main, after I merged #171, also passed: https://github.com/oneapi-src/unified-runtime/actions/runs/9364748464/job/25778404126

No clue what's going on.

**Pull request closed without merging**
