### PR TITLE
Improvements to align CTS and Spec for Memory

### PR DESCRIPTION
**Pull request by martygrant**
https://github.com/intel/llvm/pull/15619

- Add tests for UR_RESULT_ERROR_INVALID_NULL/HOST_POINTER for urMemImageCreate and urMemBufferCreate
- Add missing error condition to spec for urMemImageCreate for checking type of image description struct
- Add tests for UR_RESULT_ERROR_INVALID_NULL_HANDLE/POINTER for urMemBuffer/ImageCreateWithnativeHandle
- Remove skip for urMemImageCreateWithNativeHandle - buffer was invalid as it was never instantiated in fixture struct
- Update image format used in urMemImageTest fixture as it was invalid and likely to cause previously skipped test to fail (which now pass)
- Add missing DDI table entry for urMemImageCreateWithNativeHandle for OpenCL
- Add test for using different ur_mem_flag_t flags with urMemBufferPartition
- Add missing UR_MEM_INFO_REFERENCE_COUNT to spec for urMemGetInfo and added test for this in urMemRetain/Release
- Removed assert in L0 urMemGetInfo which would fail if mem type is not image or the query is not a context query
- Fixed potential bug with HIP urMemGetNativeHandle which would fail if the mem handle was an image because use of std::variant
-  Check if properties param is null in L0 urMemBufferCreateWithNativeHandle and set OwnNativeHandle to false by default

### CODE REVIEW

**Comment by martygrant** [comment]
@RossBrunton @hdelan @PietroGhg apologies you all reviewed a previous PR (https://github.com/oneapi-src/unified-runtime/pull/2177) for this change but I rebased a number of times fighting with CI failures and made some changes so though it would be good to just have it reviewed afresh. The main notable change is in [the hip adapter](https://github.com/oneapi-src/unified-runtime/pull/2233/files#diff-cdda61bf8ead17f141255a7bceb4231d050653676e565fde5aa6449a30a428b2R321) so image buffer types can be handled in `urMemGetNativeHandle`, and not letting some tests pass when entry points are unsupported if they aren't optional.

**Review by PietroGhg — APPROVED** [review]

**Comment by martygrant** [comment]
@oneapi-src/unified-runtime-cuda-write @oneapi-src/unified-runtime-hip-write @oneapi-src/unified-runtime-level-zero-write looking for a review for this PR please 🙏

**Review by kbenzie — APPROVED** [review]

**Review by konradkusiak97 — APPROVED** [review]
LGTM!

**Review by nrspruit — COMMENTED** [review]
LGTM for L0

**Review by nrspruit — APPROVED** [review]

**Pull request merged**
