### PR TITLE
[loader] Add more known adapters to list

### PR DESCRIPTION
**Pull request by hdelan**
Allow loader to find HIP and openCL adapters

### CODE REVIEW

**Review by pbalcer — APPROVED** [review]

**Comment by pbalcer** [comment]
Merging this risks changing default sycl behavior, so I'd hold off on merging this.

**Review by veselypeta — APPROVED** [review]
Could we increment the version of UR to prevent it being pulled into SYCL?

**Comment by kbenzie** [comment]
> Could we increment the version of UR to prevent it being pulled into SYCL?

I was indeed thinking `main` should be bumped to `v0.8` now, to differentiate it from what's in 2024.0.

**Comment by kbenzie** [comment]
> Merging this risks changing default sycl behavior, so I'd hold off on merging this.

Now we've incremented the version to 0.8 this should be okay to merge, right @pbalcer ?

**Comment by pbalcer** [comment]
> > Merging this risks changing default sycl behavior, so I'd hold off on merging this.
> 
> Now we've incremented the version to 0.8 this should be okay to merge, right @pbalcer ?

I think so, yes.

**Pull request merged**
