### PR TITLE
Add new device descriptor to query 2D block array capabilities of the Intel GPU

### PR DESCRIPTION
**Pull request by againull**
Some Intel GPU devices support 2D block array operations which may be used to optimize applications on Intel GPUs.
This extension provides a device descriptor which allows to query the 2D block array capabilities of a device.

This is exposing the following low-level compute runtime experimental extension:
https://github.com/intel/compute-runtime/blob/master/level_zero/doc/experimental_extensions/2D_BLOCK_TRANSPOSE.md
Considering that this is an experimental extension in gpu runtime level, I think it's reasonable to make it experimental at UR level as well, so I tried to follow UR documentation and added new descriptor as an experimental extension, please advice if it should be done differently.

Headers of this experimental extension are only available at compute-runtime repo and are not available here https://github.com/oneapi-src/level-zero. So, introduced changes to sparsely fetch corresponding headers from compute-runtime repo, only required headers are fetched, not entire repo.

Corresponding intel/llvm PR: https://github.com/intel/llvm/pull/15905

### CODE REVIEW

**Review by steffenlarsen — APPROVED** [review]
HIP and CUDA changes look good!

**Comment by againull** [comment]
@oneapi-src/unified-runtime-opencl-write @oneapi-src/unified-runtime-native-cpu-write Could you please take a look.

**Review by aarongreig — APPROVED** [review]

**Comment by againull** [comment]
Converting to a draft for now as question was raised in https://github.com/intel/llvm/pull/15905 if we need to expose this in higher level.

**Comment by againull** [comment]
intel/llvm PR has been approved, so could you please to merge this PR.

**Comment by againull** [comment]
urEnqueueKernelLaunchIncrementMultiDeviceMultiThreadTest.Success/NoUseEventsNoQueuePerThread  failure is unrelated as has been seen in other PRs as well, for example here: 
https://github.com/oneapi-src/unified-runtime/pull/2055
https://github.com/oneapi-src/unified-runtime/actions/runs/12010801641/job/33478467395

**Comment by igchor** [comment]
> urEnqueueKernelLaunchIncrementMultiDeviceMultiThreadTest.Success/NoUseEventsNoQueuePerThread failure is unrelated as it has been seen in other PRs as well, for example here: #2055 https://github.com/oneapi-src/unified-runtime/actions/runs/12010801641/job/33478467395

I added this to a match file: https://github.com/oneapi-src/unified-runtime/pull/2388

**Pull request merged**
