### PR TITLE
Add a DeviceGetInfo test for DEVICE_INFO_KERNEL_SET_SPECIALIZATION_CONSTANTS

### PR DESCRIPTION
**Pull request by aarongreig**
LLVM testing https://github.com/intel/llvm/pull/12268

### CODE REVIEW

**Comment by fabiomestre** [comment]
I have updated the target branch of this PR from the `adapters` branch to the `main` branch.
Development in UR is moving back to `main`. The `adapters` branch will soon be deleted.

**Review by jchlanda — APPROVED** [review]

**Review by nrspruit — APPROVED** [review]
LGTM or level zero

**Review by callumfare — APPROVED** [review]

**Review by omarahmed1111 — APPROVED** [review]
I think we could add that info to Native CPU too.

**Review by PietroGhg — APPROVED** [review]
Native CPU lgtm, thank you

**Comment by aarongreig** [comment]
absorbed into https://github.com/oneapi-src/unified-runtime/pull/1212

**Pull request closed without merging**
