### PR TITLE
Change C++ header files extension to hpp

### PR DESCRIPTION
**Pull request by igchor**
This makes it easy to distinguish them from from C headers. Until now, they both had '.h' extension.

IDEs/editors usually just look at the extension so this helps with detecting the language automaticaly.

### CODE REVIEW

**Review by PatKamin — COMMENTED** [review]
Remove new empty file source/common/ur_uma_helpers.h

**Comment by pbalcer** [comment]
You need to change the templates, not the generated files ;)

**Comment by veselypeta** [comment]
You might want to add "*.hpp" to the formatter here https://github.com/oneapi-src/unified-runtime/blob/main/CMakeLists.txt#L94

**Comment by igchor** [comment]
> Remove new empty file source/common/ur_uma_helpers.h

Done.

**Comment by igchor** [comment]
> You need to change the templates, not the generated files ;)

Done.

**Comment by igchor** [comment]
> You might want to add "*.hpp" to the formatter here https://github.com/oneapi-src/unified-runtime/blob/main/CMakeLists.txt#L94

Done.

**Pull request merged**
