### PR TITLE
[DeviceSanitizer] Exclude shadow memory from coredump file for CPU device.

### PR DESCRIPTION
**Pull request by yingcong-wu**
Currently, the coredump file includes shadow memory, which makes the coredump file crazily big and extremely slow to write to disk. This patch would not include the shadow memory in the coredump file for CPU device.

### CODE REVIEW

**Review by AllanZyne — APPROVED** [review]

**Comment by yingcong-wu** [comment]
Failures seems unrelated, will wait a few days then rerun to see if failures are still there.

**Comment by pbalcer** [comment]
> Failures seems unrelated, will wait a few days then rerun to see if failures are still there.

yes, the failures are unrelated. the fuzz test started failing recently (probably after an automatic OS update) and the E2E tests are a moving target (intel/llvm tests on different HW).
lgtm.

**Review by pbalcer — APPROVED** [review]

**Comment by yingcong-wu** [comment]
> yes, the failures are unrelated. the fuzz test started failing recently (probably after an automatic OS update) and the E2E tests are a moving target (intel/llvm tests on different HW).

Thank you for this information!

**Comment by AllanZyne** [comment]
title "Exlcude" -> "Exclude"

**Comment by yingcong-wu** [comment]
Hi @pbalcer , what should I do next for this PR? Please advise. Thank you.

**Pull request merged**
