### PR TITLE
[UR][L0] Add support for urAdapterGetLastError in L0

### PR DESCRIPTION
**Pull request by jandres742**
LLVM testing in https://github.com/intel/llvm/pull/11760

### CODE REVIEW

**Comment by jandres742** [comment]
this fixes an error in CTS test-runtime:

before:
```
[ RUN      ] urAdapterGetLastErrorTest.Success
/home/jarteaga/unified-runtime/test/conformance/runtime/urAdapterGetLastError.cpp:19: Failure
Expected equality of these values:
  uur::Result(UR_RESULT_SUCCESS)
    Which is: UR_RESULT_SUCCESS
  uur::Result(urAdapterGetLastError(adapters[0], &message, &error))
    Which is: UR_RESULT_ERROR_UNSUPPORTED_FEATURE

...

[==========] 29 tests from 9 test suites ran. (3 ms total)
[  PASSED  ] 28 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] urAdapterGetLastErrorTest.Success

```


after:

```
[----------] 4 tests from urAdapterGetLastErrorTest
[ RUN      ] urAdapterGetLastErrorTest.Success
[       OK ] urAdapterGetLastErrorTest.Success (0 ms)

...
[==========] 29 tests from 9 test suites ran. (4 ms total)
[  PASSED  ] 29 tests
```

**Comment by jandres742** [comment]
@callumfare , @kbenzie : could you take a look?

**Review by kbenzie — APPROVED** [review]
LGTM - we will merge this once a couple other PR's are in, there's a small backlog we're hoping to clear soon.

**Review by pbalcer — APPROVED** [review]

**Comment by kbenzie** [comment]
I've opened https://github.com/intel/llvm/pull/11811 combing this with #1028 and #1022 to merge into intel/llvm at the same time to accelerate merging.

**Pull request merged**
