### PR TITLE
[HIP] Re add extended deleters

### PR DESCRIPTION
**Pull request by hdelan**
Adapter-specific change from https://github.com/intel/llvm/pull/11344 .

### CODE REVIEW

**Comment by kbenzie** [comment]
Looks like this might change the results of the `test-context` CTS test. Would that be expected?

```
 5/14 Test #13: context-adapter_hip ..............***Failed    0.45 sec
-- Found Python3: /usr/bin/python3.10 (found version "3.10.12") found components: Interpreter 
End of input file or empty file.
expected: urContextSetExtendedDeleterTest.Success/AMD_HIP_BACKEND___{{.*}}_
CMake Error at /home/test-user/actions-runner/_work/unified-runtime/unified-runtime/cmake/match.cmake:74 (message):
  Failed (1): The output of test command '/usr/bin/python3.10
  /home/test-user/actions-runner/_work/unified-runtime/unified-runtime/test/conformance/cts_exe.py;--test_command;/home/test-user/actions-runner/_work/unified-runtime/unified-runtime/build/bin/test-context'
  (stored in
  /home/test-user/actions-runner/_work/unified-runtime/unified-runtime/build/test/conformance/context/_matchtmpfile)
  does not match
  '/home/test-user/actions-runner/_work/unified-runtime/unified-runtime/test/conformance/context/context_adapter_hip.match'
```

**Review by jchlanda — APPROVED** [review]

**Review by kbenzie — APPROVED** [review]

**Comment by hdelan** [comment]
@kbenzie I'm not sure if all these pending reviewers are necessary. In intel/llvm just one person on the reviewers list used to get assigned to each PR.

**Comment by kbenzie** [comment]
> @kbenzie I'm not sure if all these pending reviewers are necessary. In intel/llvm just one person on the reviewers list used to get assigned to each PR.

Correct, they are not required but they were still requested. I think I did this prior to the codeowner teams being properly setup so requested the individuals in the team.

**Review by npmiller — APPROVED** [review]

**Comment by kbenzie** [comment]
https://github.com/intel/llvm/pull/11344 checks all need to pass before we can merge according to the [Adapter Change Process](https://oneapi-src.github.io/unified-runtime/core/CONTRIB.html#adapter-change-process) though.

**Comment by hdelan** [comment]
@kbenzie checks passed here https://github.com/intel/llvm/pull/11344 . Think should be OK to merge

**Pull request merged**
