### PR TITLE
[UR] Define new test macro to catch crashes

### PR DESCRIPTION
**Pull request by veselypeta**
Define a specific conformance test macro which will fail each test that exits with a crash intead of failing the entire test suite.

If we decide to use this macro, we will need to ensure that we run the testsuites with the `--gtest_death_test_style=threadsafe`

### CODE REVIEW

**Comment by pbalcer** [comment]
That looks clunky, but I guess it's out of the way for the most part...

Maybe it would be simpler to run tests one by one? We are already going to be wrapping test execution in a script (#823), so might as well do a loop inside of it. I'm not sure what's better.

**Comment by kbenzie** [comment]
> Maybe it would be simpler to run tests one by one?

In my experience with [UnitCL](https://github.com/codeplaysoftware/oneapi-construction-kit/tree/main/source/cl/test/UnitCL) this ends up being much slower to run. If we do decide to do that though, there is a ready made tool for it [gtest-parallel](https://github.com/google/gtest-parallel).

**Comment by kbenzie** [comment]
Long term we do expect there to be no crashes in the CTS so I feel like this approach is very heavy handed way of dealing with the problem at hand. This gtest functionality is not intended to be used on every single test case but rather to test specific failure modes around process exits.

**Comment by veselypeta** [comment]
Dropping this solution in favour of #810

**Pull request closed without merging**
