### PR TITLE
[UR][L0][Bindless] Create sampled image from image and sampler descriptors

### PR DESCRIPTION
**Pull request by wenju-he**

### CODE REVIEW

**Comment by aravindksg** [comment]
@wenju-he similar to driver changes, I think we first need to finalize the interfaces first before URT implementation. is this just to test out the flow for bindless samplers? @nrspruit FYI

we also need URT JIRA to track implementation effort

**Comment by wenju-he** [comment]
> I think we first need to finalize the interfaces first before URT implementation

Yes, this PR is waiting for spec change.

> is this just to test out the flow for bindless samplers?

Yes. The flow for SYCL bindless sampler is working on DG2 with draft PRs. This draft PR is also intended as a formal patch when spec is changed.

> we also need URT JIRA to track implementation effort

I just created a URT jira.

**Comment by wenju-he** [comment]
This PR will be merged into https://github.com/oneapi-src/unified-runtime/pull/1470 when L0 spec is public and then this pr will be closed

**Comment by wenju-he** [comment]
merged into https://github.com/oneapi-src/unified-runtime/pull/1470

**Pull request closed without merging**
