### PR TITLE
[DeviceASAN] Re-use shadow if required size is not larger than last one

### PR DESCRIPTION
**Pull request by zhaomaosu**
intel/llvm: https://github.com/intel/llvm/pull/16258

### CODE REVIEW

**Review by pbalcer — APPROVED** [review]

**Review by AllanZyne — APPROVED** [review]

**Comment by pbalcer** [comment]
please create an intel/llvm PR.

**Comment by zhaomaosu** [comment]
> please create an intel/llvm PR.

Done

**Comment by martygrant** [comment]
@zhaomaosu there are some conflicts to be resolved before we can merge this

**Comment by zhaomaosu** [comment]
> there are some conflicts to be resolved before we can merge this

resolved. thanks.

**Pull request merged**
