### PR TITLE
[ur] Implement USM 2D operations

### LINKED ISSUE #83: Support sycl_ext_oneapi_memcpy2d extension
https://github.com/intel/llvm/pull/7370 introduces support for the `sycl_ext_oneapi_memcpy2d` extension by adding 3 entry points to PI: `piextUSMEnqueueFill2D`, `piextUSMEnqueueMemset2D`, and `piextUSMEnqueueMemcpy2D`, along with supporting enumerations.

Add support to the unified runtime spec, the relevant changes for the spec are in the `sycl/include/sycl/detail/pi.h` header.

### PR DESCRIPTION
**Pull request by veselypeta**
Closes #83

### CODE REVIEW

**Review by FranklandJack — APPROVED** [review]
LGTM.

**Review by kbenzie — CHANGES_REQUESTED** [review]
Blocking until https://github.com/intel/llvm/pull/7370 gets accepted.

**Comment by kbenzie** [comment]
https://github.com/intel/llvm/pull/7370 has merged, I'll review this properly soon. Could you double check things between this PR and the other still line up @veselypeta?

**Review by kbenzie — APPROVED** [review]
LGTM

**Pull request merged**
