### PR TITLE
ur: Update spec to v0.6

### PR DESCRIPTION
**Pull request by kbenzie**
Change version in preparation for oneAPI HW SIG to differentiate the current state of the specification from previous meetings.

### CODE REVIEW

**Comment by kbenzie** [comment]
I don't actually know how to do that, do you @jandres742 ?

**Comment by alycm** [comment]
I don't think that it should redirect, it makes sense to have both a "released" version at deliberate points and the live version that updates with every accepted PR.

**Comment by jandres742** [comment]
Ah ok,  we have two URLs for the spec:
https://spec.oneapi.io/unified-runtime/latest/index.html
https://oneapi-src.github.io/unified-runtime/

I guess the former is the official, updated every once in a while (like every release), and the latter is updated on every commit.

in that case, we shouldn't redirect, as one is the stable spec, and the other is the development spec.

I dont know how to update the one in  https://spec.oneapi.io/unified-runtime/latest/index.html, but I can find out. Let me ask around.

**Comment by kbenzie** [comment]
> I dont know how to update the one in https://spec.oneapi.io/unified-runtime/latest/index.html, but I can find out. Let me ask around.

Thank you!

**Pull request merged**
