### PR TITLE
[L0] Update to Loader version v1.17.44

### PR DESCRIPTION
**Pull request by nrspruit**

### CODE REVIEW

**Review by aarongreig — APPROVED** [review]

**Comment by pbalcer** [comment]
CodeQL/trivy failures are related:
```
Could not process some files due to syntax errors (3 results)
    * actions-runner/_work/unified-runtime/unified-runtime/build/_deps/level-zero-loader-src/include/zet.py#L1061C140:140: A parse error occurred while processing `/opt/actions-runner/_work/unified-runtime/unified-runtime/build/_deps/level-zero-loader-src/include/zet.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.
    * actions-runner/_work/unified-runtime/unified-runtime/build/_deps/level-zero-loader-src/include/zes.py#L2009C32:32: A parse error occurred while processing `/opt/actions-runner/_work/unified-runtime/unified-runtime/build/_deps/level-zero-loader-src/include/zes.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.
    * actions-runner/_work/unified-runtime/unified-runtime/build/_deps/level-zero-loader-src/include/ze.py#L1806C41:41: A parse error occurred while processing `/opt/actions-runner/_work/unified-runtime/unified-runtime/build/_deps/level-zero-loader-src/include/ze.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.
```

We will need to look into those GH Actions to see how to skip checking files in `_deps`.

**Comment by EwanC** [comment]
Hiya, I'm interested in using some changes that are made available https://github.com/oneapi-src/level-zero/releases/tag/v1.18.2 in command-buffer code, would it be possible to bump this tag further?  No worries if this is extra work scope outside the scope of this PR.

**Comment by pbalcer** [comment]
I'm closing this in favor https://github.com/oneapi-src/unified-runtime/pull/2208 where I've also updated CI to ignore issues in _deps.

**Comment by nrspruit** [comment]
> Hiya, I'm interested in using some changes that are made available https://github.com/oneapi-src/level-zero/releases/tag/v1.18.2 in command-buffer code, would it be possible to bump this tag further? No worries if this is extra work scope outside the scope of this PR.

I was addressing issues in the l0 spec itself so I did not want to update UR until those issues were resolved. I have "just" fixed those issues so this is now ok to move to 1.18.3

**Pull request closed without merging**
