### PR TITLE
[Bindless][Exp] Add device queries for sampled image fetch

### PR DESCRIPTION
**Pull request by przemektmalon**
Added the following queries for device capabilities of fetching sampled images:

- DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_1D_USM_EXP
- DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_1D_EXP
- DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_2D_USM_EXP
- DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_2D_EXP
- DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_3D_USM_EXP
- DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_3D_EXP

### CODE REVIEW

**Comment by przemektmalon** [comment]
Related DPC++ PR: https://github.com/intel/llvm/pull/12447

**Comment by kbenzie** [comment]
Should we close #1529?

**Comment by przemektmalon** [comment]
> Should we close #1529?

Apologies, when I created this PR I wasn't aware of #1529.

I think it's easier for me if I have control over this PR, in case I need to make changes to fix the DPC++ CI failures. So I would prefer to keep this PR and close #1529.

**Comment by kbenzie** [comment]
@przemektmalon yeah not problem, I agree it'll be easier for you to work on your own fork if any changes are necessary.

**Review by Seanst98 — APPROVED** [review]

**Review by kbenzie — APPROVED** [review]

**Comment by kbenzie** [comment]
Since this was already approved before being reverted I'll go ahead an merge this anyway.

**Pull request merged**
