### PR TITLE
[L0] Enable Immediate Command List by default given Intel DG2

### PR DESCRIPTION
**Pull request by nrspruit**
- Enabled Immediate Command list usage per queue given Intel DG2 HW.
- Removed default setting of false on windows.

### CODE REVIEW

**Review by johntfalk — APPROVED** [review]

**Review by MichalMrozek — APPROVED** [review]

**Comment by nrspruit** [comment]
After rebase, usage of immediate command lists is exposing a bug running the new tests in https://github.com/oneapi-src/unified-runtime/commit/ac7eb1717ab1d373640b62de0fdb2bf2dfa2b087 by @EwanC .

**Comment by nrspruit** [comment]
Failures seen in https://github.com/intel/llvm/pull/15054 for memcpy 2d, until that is resolved this PR is in draft.

**Comment by omarahmed1111** [comment]
@nrspruit Is this PR a WIP?

**Comment by nrspruit** [comment]
> @nrspruit Is this PR a WIP?

Hello @omarahmed1111 , yes, this patch exposes a problem in a L0 Driver so this is pending and will most likely need to be updated before it can be merged. I will remove the 0.10.x until we can get this resolved.

**Comment by nrspruit** [comment]
E2E failure is unrelated to this change.

**Comment by nrspruit** [comment]
Based on CI results here: https://github.com/intel/llvm/pull/15031 && https://github.com/intel/llvm/pull/15054 there are no failures caused by this change. The Jenkins jobs are randomly failing.

**Comment by nrspruit** [comment]
awaiting one more re-review before ready to merge.

**Review by winstonzhang-intel — APPROVED** [review]

**Pull request merged**
