### PR TITLE
[docs] Printing C API html docs

### PR DESCRIPTION
**Pull request by PatKamin**
Generate HTML documentation for printing C API.
[preview](https://patkamin.github.io/unified-runtime/core/api.html#print)

### CODE REVIEW

**Review by pbalcer — APPROVED** [review]
how does it look like generated?

**Comment by PatKamin** [comment]
> how does it look like generated?

You can see it [here](https://patkamin.github.io/unified-runtime/core/api.html#print).

**Review by bratpiorka — APPROVED** [review]

**Review by kswiecicki — APPROVED** [review]

**Comment by PatKamin** [comment]
Converted to draft to make sure that the #930 is merged first.

**Review by kbenzie — APPROVED** [review]

**Comment by PatKamin** [comment]
> please rebase. 

Done

**Review by kbenzie — APPROVED** [review]

**Review by kswiecicki — APPROVED** [review]

**Pull request merged**
