### PR TITLE
Wrap linker flags on Windows for IntelLLLVM

### PR DESCRIPTION
**Pull request by Maetveis**
The Intel C++ compiler requires linker flags to be wrapped, because CMake passes them through the compiler driver.
Prefix linker options with `LINKER:`.
CMake will transorm it to the appropriate flag for the compiler driver: (Nothing for MSVC or clang-cl, and /Qoption,link for icx), so this will work for other compilers and for earlier CMake versions too.

> [!NOTE]  
> Requires updating the fetched versions of UMF and Level Zero to versions that include the fix for the same problem. I tested locally with `-DUMF_TAG=e6ff45e1636bd172117bab6d9f4d00638113f592 -DUR_LEVEL_ZERO_LOADER_TAG=v1.18.1`.

Fixes: #2178

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
👍 LGTM

FYI, similar PR was already verified and merged in umf: https://github.com/oneapi-src/unified-memory-framework/pull/772

**Comment by lukaszstolarczuk** [comment]
I can try and add an icx build in the CI, if you want...? (I'm doing such workflow for UMF at the moment)

**Review by ldorau — APPROVED** [review]

**Review by kbenzie — APPROVED** [review]

**Comment by Maetveis** [comment]
Ping, can we get this merged? I don't have merge access myself.

**Comment by kbenzie** [comment]
> Ping, can we get this merged? I don't have merge access myself.

@oneapi-src/unified-runtime-level-zero-write still need to approve this.

**Comment by kbenzie** [comment]
> @kbenzie can you approve the workflows? I rebased to see if the CI failures go away or if I will need to investigate.

The pull request labeler job is expected to fail for PRs from people who aren't a memory of the UR traige team. If there are e2e failures that doesn't necessarily block merging as long as we can determine they are not related to these changes.

**Review by nrspruit — APPROVED** [review]
LGTM for L0

**Comment by Maetveis** [comment]
@aarongreig bump, should I look into the failures? I am not familiar with L0 and I don't expect runtime failures from this. This blocking some other future work for me.

**Comment by pbalcer** [comment]
No, those failures are expected.

**Comment by Maetveis** [comment]
> No, those failures are expected.

Okay, Thank you. Lets get this merged then pretty please.

**Comment by Maetveis** [comment]
ping @callumfare @nrspruit @pbalcer

**Comment by callumfare** [comment]
@Maetveis Please resolve the conflicts and I'll make sure this gets merged soon

**Comment by Maetveis** [comment]
Since #2100 was reverted and it had a CMake fix that was needed here (the source of the conflict previously) I restored this PR to how it was before conflict resolution.

Ping @callumfare, please merge this ASAP.

**Pull request merged**
