### PR TITLE
[UR][L0] Add support for zeCommandListHostSynchronize

### PR DESCRIPTION
**Pull request by jandres742**
Instead of creating an event, appending, and synchronizing it on it to wait for all commands in an immediate command list, emit a zeCommandListHostSynchronize instead.

LLVM testing: https://github.com/intel/llvm/pull/10003

### CODE REVIEW

**Comment by jandres742** [comment]
@smaslov-intel : please check.

**Review by smaslov-intel — APPROVED** [review]
LGTM

**Comment by jandres742** [comment]
@kbenzie : please check and approve + merge if all is correct.

**Review by kbenzie — APPROVED** [review]

**Comment by kbenzie** [comment]
I've opened https://github.com/intel/llvm/pull/11811 combing this with #1033 and #1022 to merge into intel/llvm at the same time to accelerate merging.

**Pull request merged**
