### PR TITLE
Add missing affinity domains

### PR DESCRIPTION
**Pull request by FranklandJack**
Add missing cache affinity domains to device affinity domains
enumeration. Fixes https://github.com/oneapi-src/unified-runtime/issues/115.

### CODE REVIEW

**Comment by FranklandJack** [comment]
This might be worth reconsidering. 

Looking at the usage of `PI_DEVICE_AFFINITY_DOMAIN_L(1|2|3|4)_CACHE` none of the adaptors actually handle these enumeration values, so although they would be required replace the usage in the DPC++ codebase as is, perhaps they aren't really needed by the DPC++ codebase to begin with unless there are out of tree adapters using them?

**Comment by kbenzie** [comment]
> ... perhaps they aren't really needed by the DPC++ codebase to begin with unless there are out of tree adapters using them?

Does make me wonder if we should hold off making this change then.

**Comment by FranklandJack** [comment]
> > ... perhaps they aren't really needed by the DPC++ codebase to begin with unless there are out of tree adapters using them?
> 
> Does make me wonder if we should hold off making this change then.

Yeah I think so, this may be true of other missing PI features. But it would be useful to get confirmation from engineers who are familiar with that codebase.

**Comment by FranklandJack** [comment]
I'm closing this since there is a question of if it is actually required.

**Pull request closed without merging**
