### PR TITLE
Deterministic mode and improvements for match.py

### PR DESCRIPTION
**Pull request by RossBrunton**
Some improvements for match.py:
* Added a {{NONDETERMINISTIC}} tag, which indicates that the match file results need not be in order.
* When printing output, line numbers and the "interesting line" are provided.
* Fix incorrect index being used when no lines matching a "match" line are found.

In addition, all the conformance test match files are marked as "{{NONDETERMINISTIC}}", as they may be ran in different orders depending on compile flags.

### CODE REVIEW

**Comment by RossBrunton** [comment]
Example of new output format:
```
#### GTEST_OUTPUT_END ####
Input line 1 has no match line
is:       urEnqueueWriteHostPipeTest.InvalidNullHandleQueue/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________

------ Input Lines -------------------------------------------------------------
>   1| urEnqueueWriteHostPipeTest.InvalidNullHandleQueue/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
    2| urEnqueueWriteHostPipeTest.InvalidNullHandleProgram/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
    3| urEnqueueWriteHostPipeTest.InvalidNullPointerPipeSymbol/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
    4| urEnqueueWriteHostPipeTest.InvalidNullPointerBuffer/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
    5| urEnqueueWriteHostPipeTest.InvalidEventWaitList/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
    6| urEnqueueReadHostPipeTest.InvalidNullHandleQueue/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
    7| urEnqueueReadHostPipeTest.InvalidNullHandleProgram/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
    8| urEnqueueReadHostPipeTest.InvalidNullPointerPipeSymbol/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
    9| urEnqueueReadHostPipeTest.InvalidNullPointerBuffer/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
   10| urEnqueueReadHostPipeTest.InvalidEventWaitList/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
   11| urEnqueueUSMPrefetchTest.InvalidSizeTooLarge/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
   12| urEnqueueUSMMemcpyTest.WaitForDependencies/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
   13| urEnqueueUSMAdviseTest.InvalidSizeTooLarge/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
   14| urEnqueueUSMFill2DNegativeTest.OutOfBounds/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
   15| urEnqueueMemImageWriteTest.InvalidOrigin1D/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
   16| urEnqueueMemImageWriteTest.InvalidOrigin2D/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
   17| urEnqueueMemImageWriteTest.InvalidOrigin3D/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
   18| urEnqueueMemImageWriteTest.InvalidRegion1D/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
   19| urEnqueueMemImageWriteTest.InvalidRegion2D/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
   20| urEnqueueMemImageWriteTest.InvalidRegion3D/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
   21| urEnqueueMemImageReadTest.InvalidOrigin1D/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
   22| urEnqueueMemImageReadTest.InvalidOrigin2D/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
   23| urEnqueueMemImageReadTest.InvalidOrigin3D/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
   24| Aborted
------ Match Lines -------------------------------------------------------------
    1| {{NONDETERMINISTIC}}
    2| {{OPT}}urEnqueueEventsWaitTest.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}_
    3| {{OPT}}urEnqueueKernelLaunchTest.InvalidKernelArgs/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}_
    4| {{OPT}}urEnqueueKernelLaunchKernelWgSizeTest.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}_
    5| {{OPT}}urEnqueueKernelLaunchKernelSubGroupTest.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}_
    6| {{OPT}}urEnqueueKernelLaunchUSMLinkedList.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}__UsePoolEnabled
    7| {{OPT}}urEnqueueKernelLaunchUSMLinkedList.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}__UsePoolDisabled
    8| {{OPT}}urEnqueueMemBufferCopyRectTestWithParam.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}___copy_2d_3d
    9| {{OPT}}urEnqueueMemBufferCopyRectTestWithParam.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}___copy_3d_2d
   10| {{OPT}}urEnqueueMemBufferReadRectTestWithParam.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}___write_non_zero_offsets_2D
   11| {{OPT}}urEnqueueMemBufferReadRectTestWithParam.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}___write_different_buffer_sizes_2D
   12| {{OPT}}urEnqueueMemBufferReadRectTestWithParam.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}___write_column_2D
   13| {{OPT}}urEnqueueMemBufferReadRectTestWithParam.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}___write_3d_with_offsets
   14| {{OPT}}urEnqueueMemBufferReadRectTestWithParam.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}___write_2d_3d
   15| {{OPT}}urEnqueueMemBufferReadRectTestWithParam.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}___write_3d_2d
   16| {{OPT}}urEnqueueMemBufferWriteRectTestWithParam.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}___write_3d_with_offsets
   17| {{OPT}}urEnqueueMemBufferWriteRectTestWithParam.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}___write_2d_3d
   18| {{OPT}}urEnqueueMemBufferWriteRectTestWithParam.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}___write_3d_2d
   19| {{OPT}}urEnqueueMemImageCopyTest.InvalidSize/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}___1D
   20| {{OPT}}urEnqueueMemImageCopyTest.InvalidSize/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}___2D
   21| {{OPT}}urEnqueueMemImageCopyTest.InvalidSize/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}___3D
   22| {{OPT}}urEnqueueMemImageReadTest.InvalidOrigin1D/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}_
   23| {{OPT}}urEnqueueMemImageReadTest.InvalidOrigin2D/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}_
   24| {{OPT}}urEnqueueMemImageReadTest.InvalidOrigin3D/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}_
   25| {{Segmentation fault|Aborted}
```

**Comment by aarongreig** [comment]
Nice, looks like a much needed upgrade for the output. I think with the rate of files that need the new tag we could consider just making `{{NONDETERMINISTIC}}` the default behaviour, not sure how much value we're getting from enforcing in order for what I assume to be a minority of cases.

**Comment by pbalcer** [comment]
I don't believe we shuffle the tests, right? So when does matching fail without `NONDETERMINISTIC`?

I agree with Aaron that given you need to add this to so many match files, it may make sense to make it default. However, we use match.py also for other tests (like the logger output), where ordering does matter.
So my suggestion would be to add an argument to the match.py, something like `--nondeterministic-by-default` (but shorter :-)), that is then passed to CTS only (https://github.com/oneapi-src/unified-runtime/blob/main/test/conformance/CMakeLists.txt#L24).

**Comment by RossBrunton** [comment]
> So when does matching fail without `NONDETERMINISTIC`?

`-flto` at least; I think changing how linking works changes the order tests are scheduled in. For example, here's some output from running the test suite in a `-flto` build:

```
#### GTEST_OUTPUT_END ####
Line 1 does not match
is:       urProgramGetNativeHandleTest.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
expected: urProgramCreateWithNativeHandleTest.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}_
------ Input Lines -------------------------------------------------------------
>   1| urProgramGetNativeHandleTest.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
    2| urProgramGetFunctionPointerTest.InvalidKernelName/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
    3| urProgramGetBuildInfoTest.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F__________________UR_PROGRAM_BUILD_INFO_STATUS
    4| urProgramCreateWithNativeHandleTest.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
    5| urProgramCreateWithNativeHandleTest.InvalidNullHandleContext/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
    6| urProgramCreateWithNativeHandleTest.InvalidNullPointerProgram/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__UHD_Graphics_770__X____F________________
------ Match Lines -------------------------------------------------------------
>   1| urProgramCreateWithNativeHandleTest.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}_
    2| urProgramCreateWithNativeHandleTest.InvalidNullHandleContext/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}_
    3| urProgramCreateWithNativeHandleTest.InvalidNullPointerProgram/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}_
    4| urProgramGetBuildInfoTest.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}_UR_PROGRAM_BUILD_INFO_STATUS
    5| urProgramGetFunctionPointerTest.InvalidKernelName/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}_
    6| urProgramGetNativeHandleTest.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}_
    7| {{OPT}}urProgramLinkErrorTest.LinkFailure/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}_
    8| {{OPT}}urProgramLinkErrorTest.SetOutputOnLinkError/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___{{.*}}_
------ Ignored Lines -----------------------------------------------------------
--------------------------------------------------------------------------------
```

> So my suggestion would be to add an argument to the match.py, something like --nondeterministic-by-default (but shorter :-)), that is then passed to CTS only (https://github.com/oneapi-src/unified-runtime/blob/main/test/conformance/CMakeLists.txt#L24).

I'm a bit hesitant about this, it means the files are no longer "self-contained". If you're trying to debug test failures and want to run the matching script outside the build, you need to remember whether or not to add the "deterministic" flag or not.

@pbalcer

**Comment by pbalcer** [comment]
> I'm a bit hesitant about this, it means the files are no longer "self-contained". If you're trying to debug test failures and want to run the matching script outside the build, you need to remember whether or not to add the "deterministic" flag or not.

Ok, makes sense, then I think we should just keep it as is, with `{{NONDETERMINISTIC}}` at the beginning of every CTS match file. I wouldn't want this behavior to be by default, since it may be confusing when working on normal tests. Using match files for CTS failures was always meant to be temporary (although I'm beginning to think it's one of those temporary solutions that become permanent...).

**Review by EwanC — APPROVED** [review]
command-buffer match file changes LGTM, will leave the design decision on a `match.py` flag v `{{NONDETERMINISTIC}` to the repo maintainers

**Pull request merged**
