### PR TITLE
[DeviceSanitizer] refactor options

### PR DESCRIPTION
**Pull request by yingcong-wu**
A follow-up of https://github.com/oneapi-src/unified-runtime/pull/1862, refactor AsanOptions to avoid initialization deadlock.

SYCLOS PR: https://github.com/intel/llvm/pull/14579

### CODE REVIEW

**Review by pbalcer — APPROVED** [review]

**Comment by yingcong-wu** [comment]
I disagree, AsanOptions class is nothing but a helper that parses and validates the options, it does not have any implementation details. And move it to context would allow easy access to it just like the logger.

**Comment by AllanZyne** [comment]
> I disagree, AsanOptions class is nothing but a helper that parses and validates the options, it does not have any implementation details. And move it to context would allow easy access to it just like the logger.

"options" is too general in context, since we will support other sanitizers in the future. 
I suggest you can rename it to "asanOptions", or move it under interceptor.

**Comment by AllanZyne** [comment]
I prefer to move it under interceptor, and create a new method "getOption()" for outside code.

**Comment by AllanZyne** [comment]
Maybe "getContext()->interceptor" will be rename to "asanInterceptor" in the future. 
Or we'll create a base class for interceptor, since sanitizers can not be enabled at the same time.

**Comment by yingcong-wu** [comment]
> Maybe "getContext()->interceptor" will be rename to "asanInterceptor" in the future.
> Or we'll create a base class for interceptor, since sanitizers can not be enabled at the same time.

That sounds reasonable. If we want to put many sanitizers in the same context, then there are many refactoring to be done. And since we use the name `UR_LAYER_ASAN_OPTIONS` which is specified for ASAN, then it is more reasonable to put in under a ASAN interceptor than put in in a general context.

I would close this PR and this refactor can be in the same change of the ASAN interceptor refactoring.

**Pull request closed without merging**
