### PR TITLE
Change ur_bool_t to uint32_t

### PR DESCRIPTION
**Pull request by jandres742**
This to match the boolean type used in SYCL, where pi_bool is also uint32_t.

Resolves: #555

### CODE REVIEW

**Comment by kbenzie** [comment]
We actually have a pi2ur workaround for this size mismatch called `fixupReturnValues()`.

**Comment by jandres742** [comment]
> fixupReturnValues

thanks @kbenzie . This error came from a value UR L0 is returning in piDeviceGetInfo, and there we are calling fixupInfoValueTypes. So maybe the WA is not working completely. Should we proceed with this PR so we can eventually remove the WA or would you prefer to keep the WA?

**Comment by kbenzie** [comment]
Lets discuss this in the WG call shortly.

**Comment by kbenzie** [comment]
Closing for reason described in #555

**Pull request closed without merging**
